# Generated by Django 3.2.4 on 2021-06-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_communtingtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommuntingTime',
            new_name='CommutingTime',
        ),
        migrations.RenameField(
            model_name='commutingtime',
            old_name='AAW',
            new_name='arrive_at_work',
        ),
    ]
