# Generated by Django 3.2.4 on 2021-06-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210629_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
