# Generated by Django 3.2.4 on 2021-06-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_commutingtime_arrive_at_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commutingtime',
            options={'verbose_name_plural': '出社時間'},
        ),
    ]
