# Generated by Django 3.2.4 on 2021-06-29 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_commutingtime_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutingtime',
            name='leave',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 17, 37, 55, 284509), verbose_name='退社時間'),
        ),
    ]
