# Generated by Django 3.2.4 on 2021-06-29 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_commutingtime_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutingtime',
            name='leave',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 17, 47, 42, 40803), verbose_name='退社時間'),
        ),
    ]
