# Generated by Django 3.2.4 on 2021-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_commutingtime_leave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commutingtime',
            options={'verbose_name_plural': '勤怠管理'},
        ),
        migrations.AlterField(
            model_name='commutingtime',
            name='arrive_at_work',
            field=models.DateTimeField(verbose_name='出社時間'),
        ),
        migrations.AlterField(
            model_name='commutingtime',
            name='leave',
            field=models.DateTimeField(verbose_name='退社時間'),
        ),
    ]
