# Generated by Django 3.2.4 on 2021-06-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210629_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutingtime',
            name='arrive_at_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出社時間'),
        ),
        migrations.AlterField(
            model_name='commutingtime',
            name='leave',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退社時間'),
        ),
    ]
