# Generated by Django 3.2.4 on 2021-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_commutingtime_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutingtime',
            name='count',
            field=models.IntegerField(default=0, verbose_name='合計労働時間'),
        ),
    ]
