# Generated by Django 3.2.4 on 2021-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_commutingtime_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutingtime',
            name='payment',
            field=models.IntegerField(default=1000, verbose_name='時給'),
        ),
    ]
