# Generated by Django 3.2.4 on 2021-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20210704_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commutingtime',
            name='per_day',
        ),
        migrations.AddField(
            model_name='commutingtime',
            name='count',
            field=models.IntegerField(default=0, verbose_name='一日の勤務時間'),
        ),
    ]
